"use strict";
var function_wrapper_1 = require("./function-wrapper");
exports.wrapper = function_wrapper_1.wrapper;
var passed_time_1 = require("./passed-time");
exports.passedTimeMessage = passed_time_1.passedTimeMessage;
var log_response_1 = require("./log-response");
exports.logResponse = log_response_1.logResponse;
var fetch_1 = require("./fetch");
exports.customFetch = fetch_1.customFetch;
var is_json_1 = require("./is-json");
exports.isJson = is_json_1.isJson;
exports.isHtml = is_json_1.isHtml;
exports.isPicture = is_json_1.isPicture;
var axios_1 = require("./axios");
exports.createAxios = axios_1.createAxios;
